# Maven Maven 
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, more::
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
variables:
  - group: aryantest

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs

- task: ArchiveFiles@2
  displayName: 'Zip Aumentum'    
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)\*'
    includeRootFolder: false
    archiveType: 'zip'      
    archiveFile: '$(Build.ArtifactStagingDirectory)/sample.zip'

- task: AzureFileCopy@3
  displayName: 'Copy Aumentum zip to storage'
  inputs:
    sourcePath: '$(Build.ArtifactStagingDirectory)/sample.zip'
    azureSubscription: 'df3588cd-396f-4c36-8da8-3b78a798963c'
    destination: azureBlob
    storage: $(StorageAccountName)
    containerName: 'build'
    blobPrefix: 'aumentum'

