# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# Practice 
#Tra practice
trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  - group: testvars

jobs:
- job: PrepareEnvironmentJob
  steps:

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
  - task: PowerShell@2
    displayName: 'Determine the name of this stack that the Pipeline is excuting for.'
    inputs:
      targetType: 'filePath'    
      filePath: 'deployment\ConfigureStackName.ps1'
      errorActionPreference: 'stop'
  
  # - task: AzureResourceGroupDeployment@2
  #   displayName: 'Run Application GateWay ARM Deployment'
  #   inputs:
  #     azureSubscription: '$(AzureSubscription)'
  #     resourceGroupName: $(DeployResourceGroupName)
  #     location: '$(DeployLocation)'
  #     templateLocation: 'Linked artifact'
  #     csmFile: myarm.json
  #     overrideParameters: >-
  #         -publicIPAddressName $(name) 

  #     deploymentOutputs: 'AGwayOutput'
  # - task: AzureResourceGroupDeployment@2
  #   #condition: and(succeeded(), ne(variables['PrepCicd.DeployWorkload'], 'NULL'))
  #   #thanks hello
  #   displayName: 'Deploy Aumentum Agent ARM Deployment'
  #   inputs:
  #     azureSubscription: '$(AzureSubscription)'
  #     resourceGroupName: $(DeployResourceGroupName)
  #     location: '$(DeployLocation)'
  #     templateLocation: 'Linked artifact'
  #     csmFile: 'create-azure-vm.json'
  #     overrideParameters: >-
  #         -stackName $(DeployStackName)
  #         -subnetName '$(SubNet)'
  #         -virtualNetworkId $(Netid)
  #         -location $(DeployLocation)

  #     deploymentOutputs: 'ArmOutput'
  # - task: AzureResourceGroupDeployment@2
  #   displayName: 'deploy 1 app service 3 DB VM'
  #   inputs:
  #     azureSubscription: '$(AzureSubscription)'
  #     resourceGroupName: $(DeployResourceGroupName)
  #     location: '$(DeployLocation)'
  #     templateLocation: 'Linked artifact'
  #     csmFile: arm.json
  #     overrideParameters: >-
  #         -adminPassword "Satish@19899"
    - task: AzureResourceGroupDeployment@2
      displayName: 'deploy appsvc'
      inputs:
        azureSubscription: '$(AzureSubscription)'
        resourceGroupName: $(DeployResourceGroupName)
        location: '$(DeployLocation)'
        templateLocation: 'Linked artifact'
        csmFile: deployment/appsvc.json
        overrideParameters: >-
            -appplan "aryanappsvcplan"